sudo: false
language: node_js
node_js:
  - "node"
script:
  - yarn cover
  - yarn build
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
after_success:
  - yarn release
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules